### ISSUE TITLE
Make bootstrap-servers a required field

### ISSUE THREAD

**Issue by matzew** [openshift-knative/knative-kafka-operator#9]
this is not optional:

https://github.com/openshift-knative/knative-kafka-operator/blob/master/pkg/apis/eventing/v1alpha1/knativeeventingkafka_types.go#L23-L24

the channel does require accessible URI to a kafka cluster (where ever that is... it needs to be accessible from the cluster)

**Comment by matzew** [comment]
Also, I think changing that (e.g. `k edit knativeeventingkafka knative-eventing-kafka -n knative-eventing`) should reflect in an update of the underlying `kafka-channel-controller-config` ConfigMap

**Comment by syedriko** [comment]
https://github.com/openshift-knative/knative-kafka-operator/pull/14

**Comment by matzew** [comment]
fixed
